### ISSUE TITLE
https://repo.ondevice.io/install_deb.sh points to a 404 response of nginx

### ISSUE THREAD

**Issue by teamgroove** [ondevice/ondevice-packaging#4]
https://repo.ondevice.io/install_deb.sh

doesn't deliver the bash-script, instead a 404 html-page

**Comment by mreithub** [comment]
Hi, thanks for reporting.

The information in this repo (and on the ondevice.io homepage) was outdated and has been fixed now.

The script has been renamed from `install_deb.sh` to `install.sh` because it should now be able to install on pretty much any Linux or macOS system.

The new one-liner is:

```sh
curl https://repo.ondevice.io/install.sh | sudo bash -
```
